# Generated by Django 3.0.4 on 2020-06-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameMode', models.CharField(max_length=32)),
                ('result', models.BooleanField()),
                ('timeElapsed', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discordName', models.CharField(max_length=32)),
                ('leagueName', models.CharField(max_length=16)),
                ('registeredKills', models.IntegerField()),
                ('registeredAssits', models.IntegerField()),
                ('registeredDamage', models.IntegerField()),
            ],
        ),
    ]
